### ISSUE TITLE
Implement usage of datasource behind enabled Grafana2 datasource proxy.

### ISSUE THREAD

**Issue by anryko** [anryko/grafana-influx-dashboard#12]
Grafana2 has a datasource proxy feature and at the moment getdash will not work for datasources with proxy enabled.

**Comment by wr0ngway** [comment]
:+1:

**Comment by anryko** [comment]
Done https://github.com/anryko/grafana-influx-dashboard/commit/929bc728c8c157ecfdb9307a2bce427a750738a7.
