### ISSUE TITLE
Add InfluxDB v0.9 support.

### ISSUE THREAD

**Issue by anryko** [anryko/grafana-influx-dashboard#16]
Related to: https://github.com/anryko/grafana-influx-dashboard/issues/10

**Comment by szop85** [comment]
Hello anryko,

who is the InfluxDB v0.9 support implementation going on? Any progress so far :)?

Cheers,
David

**Comment by anryko** [comment]
Hi David,
I plan to give it a try over the weekend so you can expect something to test on Mon :).

**Comment by szop85** [comment]
Awesome news! :)

**Comment by anryko** [comment]
This will take more time than I initially anticipated. Not only influxdb sql and data representation have changed but grafana's query editor target format for influxdb 0.9 was changed as well. I will proceed working on it.

**Comment by szop85** [comment]
Keep up going with you great work :)!

**Comment by anryko** [comment]
At the moment only system group metrics configuration was changed to support InfluxDB v0.9. Additionally there is an issue with 'value' modifiers. Like mirroring down the graph with 'value*-1'. It is not supported the same way in v0.9. Nevertheless, here is something to test :).

**Comment by anryko** [comment]
With this recent addition to Grafana (https://github.com/grafana/grafana/issues/2708) I should be able to implement 'value' modifiers.

**Comment by szop85** [comment]
Thanks for the info,

I'll give it a try next weekend :)

Cheers,
Szop

**Comment by anryko** [comment]
InfluxDB v0.9 should be fully functional now except the CPU issue mentioned in #17. I created influxdb_v0.8 branch and after updating documentation in influxdb_v0.9 branch I'm going to merge in to the master and close this issue.

**Comment by anryko** [comment]
Done https://github.com/anryko/grafana-influx-dashboard/commit/4a19e9e2025654a84c0d51edfaaca690a8ea7c33.
