### ISSUE TITLE
grafana 3.0-pre1 dropped... will this dashboard work?

### ISSUE THREAD

**Issue by lawre** [anryko/grafana-influx-dashboard#38]
subject says it all

**Comment by lawre** [comment]
I just tried with 3.0 and got the following error:
```
Script Error
Please make sure it exists and returns a valid dashboard
```

**Comment by anryko** [comment]
Hi lawe,
I didn't had a chance to test the dash with 3.0 yet. I plan to reserve couple of hours and fix it on Tue. Sorry for the inconvenience.

**Comment by nordewal** [comment]
+1
Especially looking forward to retention policy seletion support. From grafana CHANGELOG.md: 

> InfluxDB: Support for policy selection in query editor, closes #2018

Will you address this too?

**Comment by anryko** [comment]
Hi nordewal,
All getdash doese is generates json for the dashboard based on the influxdb data and getdash plugin configs, so grafana editor features are not affected and should work as advertised.

**Comment by anryko** [comment]
Hi lawre,
Where can I get 3.0-pre deb package for ubuntu? I'm not too excited about building grafana from sources and can't locate the deb to download.

**Comment by anryko** [comment]
Grafana 3.0 beta was shipped. Added beta support :).
