### ISSUE TITLE
Custom influx Port

### ISSUE THREAD

**Issue by JanKraljic** [anryko/grafana-influx-dashboard#42]
I am missing something. 

Where and how can I configure InfluxDB since is not on standard Influx port?

Thx

**Comment by anryko** [comment]
Hi Jan,
InfluxDB connection configuration is fetched from Grafana itself. All you have to do is configure Grafana data source correctly, using Grafana GUI Admin mode.

**Comment by JanKraljic** [comment]
Hi Andrej, 

Sorry for trouble. There are different names of sources due to usage of Telegram.
