### ISSUE TITLE
Missing query separator

### ISSUE THREAD

**Issue by dhoppe** [anryko/grafana-influx-dashboard#52]
I use your scripted dashboard in the following environment:

- Debian 8
- Collectd 5.5.1
- Grafana 2.6.0
- InfluxDB 0.12.1

Unfortunately I get several error messages about a missing query separator.
![Error](http://www.debian-solutions.de/grafana-influx-dashboard01.png)

As you can see the selects are just seperated by an space instead of ;.
![Query](http://www.debian-solutions.de/grafana-influx-dashboard02.png)

I use the default plugins of Collectd, but this should not matter. Do you have any idea what went wrong?

**Comment by dhoppe** [comment]
I was able to solve this issue, by upgrading Grafana to version 3.0.0-beta. 

According to the documentation of [InfluxDB](https://docs.influxdata.com/influxdb/v0.12/tools/#grafana-graphs-and-dashboards-http-docs-grafana-org-datasources-influxdb) the Query Editor of Grafana 2.6 is not compatible with InfluxDB 0.11.x or 0.12.x.

**Comment by anryko** [comment]
Nice. Thanks for sharing.
