### ISSUE TITLE
Missing db parameter when using proxy mode on graphite

### ISSUE THREAD

**Issue by toed** [anryko/grafana-influx-dashboard#53]
If the connection to influxdb is using proxymode, I cannot get it to work.
`query?q=SHOW TAG VALUES FROM load_midterm WITH KEY = host`
I always get 
`
  "results": [
    {
      "error": "database name required"
    }
  ]
}
`
Back in response.

But If I change the datasource to use direct mode instead, it is working.

**Comment by anryko** [comment]
Hi toed,

Please clarify grafana version, influxdb version and getdash branch you are having this trouble with.

**Comment by toed** [comment]
It was the latest of everything, i think.
Influxdb 0.12, grafana 3 and the master-branch of getdash

**Comment by anryko** [comment]
Should work now. Please test.
