### ISSUE TITLE
/api/datasources endpoint not accessible in 3.0.1 for non-Admin users

### ISSUE THREAD

**Issue by tkuehne-deliveryhero** [anryko/grafana-influx-dashboard#56]
Hi anryko! 😃 

After upgrading Grafana to 3.0.1 unfortunately the scripted dashboard doesn't load (gives blank page), when logged in without admin privileges.
That seems to be caused by the "/api/datasources" endpoint not being publicly accessible anymore. It returns:

`{"message":"Permission denied"}`

with such a user.

Are you aware of this? How could this be worked around?
Maybe providing an API key in getdash configuration would be an option?

Cheers,

 Tobias.

**Comment by anryko** [comment]
Hey Tobias!

I think I fixed the issue. Please confirm.

**Comment by tkuehne-deliveryhero** [comment]
Confirmed! 👍 

Thanks for fast response.
