### ISSUE TITLE
Please make sure it exists and returns a valid dashboard

### ISSUE THREAD

**Issue by yangdehua** [anryko/grafana-influx-dashboard#57]
dashboard/script/getdash.js

Script Error
Please make sure it exists and returns a valid dashboard

hello , how to solve this problem?

thanks so much

**Comment by anryko** [comment]
Hi yangdehua,

Please provide grafana version, influxdb version and getdash branch you are using.

**Comment by noesedeno** [comment]
Hi,

I am trying to create a new scripted dashboard, but keep getting "Please make sure it exists and returns a valid dashboard", Is there a log that has some details about the errors?

**Comment by anryko** [comment]
Hi @noesedeno,

You should open a JS console in your browser and check what is going on there. In my experience the most common problem is datasource misconfiguration or there might be no data in influxdb.

**Comment by noesedeno** [comment]
Thank you very much.

**Comment by anryko** [comment]
@noesedeno you are welcome :).
