### ISSUE TITLE
Missing u= & p= parameter when using proxy mode on influxdb

### ISSUE THREAD

**Issue by smeapng** [anryko/grafana-influx-dashboard#58]
Hello,

When my influxdb datasource is configured in proxy mode, getDash does not work because it fails to recuperate the parameter user and password.

db=collectd&u=undefined&p=undefined&q=SHOW%20TAG%20VALUES%20FROM%20load_midterm%20WITH%20KEY%20%3D%20host%3B

{"error":"user not found"}

If I get the right user and password in place of "undefined" or if I connect the direct datasource that works.

Grafana : 3.0.4
InfluxDB: 0.13
Master branch of grafana-influx-dashboard

Thank you.

Cordially.

**Comment by anryko** [comment]
Hi smeapng,
Unfortunately I wasn't able to exactly reproduce reported issue. However, I might have figured out where the problem is. Please confirm if last commit changed anything for you.

Thanks a lot for reporting this bug!

**Comment by smeapng** [comment]
Hello anryko,

It's good for me now, Proxy and direct mode works.

Thank you for this rapid correction.

Cordially.
