### ISSUE TITLE
[Request] Integrate multiple host selection.

### ISSUE THREAD

**Issue by smeapng** [anryko/grafana-influx-dashboard#59]
Hello,

Is it possible to integrate into the script the ability to choose multiple server? To enable comparison servers. A similar method to the template grafana.

Thank you for your reply.

Cordially.

**Comment by anryko** [comment]
Hi smeapng,
Thanks for the inspiration to do that :)

Now regex and list hostname queries are supported. So something like this is possible:
```bash
http://localhost:3000/dashboard/script/getdash.js?host=vagrant-ubuntu-precise-64,vagrant-ubuntu-precise-01&span=6
http://localhost:3000/dashboard/script/getdash.js?host=vagrant-ubuntu-precise-(01|64)&span=6
http://localhost:3000/dashboard/script/getdash.js?host=vagrant-ubuntu-precise-0*&span=6
```

**Comment by smeapng** [comment]
Hi anryko,

Thank you very much, it is much more powerful now that you can have multiple host on the same dashboard.

It's really nice that you take time to my requests and whatsoever integrated as quickly.

Cordially.

PS: If in the future you took it the desire to incorporate the possibility to have multiple host on the same graph, if would be wonderful :)
