### ISSUE TITLE
[Request] Integrate the opportunity to search a host.

### ISSUE THREAD

**Issue by smeapng** [anryko/grafana-influx-dashboard#60]
Hello anryko,

Is it possible to integrate in the script getDash, the ability to search a host ?

You tell me that ctrl + f works too;) but the host list when we want to have many hosts become heavier.

Thank you for your reply.

Cordially.

**Comment by anryko** [comment]
Hi smeapng,
Please share more of your vision how this might work and be better than Ctrl+f. At the moment I see no advantages of having the search field on the top of hosts list.

**Comment by smeapng** [comment]
Hi anryko,

I imagined something that looks a little bit variable and template on grafana.
Ex: SHOW TAG VALUES WITH KEY = "host"

![image](https://cloud.githubusercontent.com/assets/13557390/15782901/45dcc244-29ac-11e6-8930-6c80b251c97e.png)

Something that finds a host and choose hosts simply.

This is just an observation, after it can be impossible to do it from a JS script or it does not match can not be the philosophy that you want to give to your script.

Cordially.

**Comment by anryko** [comment]
@smeapng, I experimented with your suggestion and pushed a new branch for testing. Looks more useful then what i initially expected. Could you please test it and let me know what you think?

**Comment by smeapng** [comment]
Hi @anryko ,

Thank you for these rapid changes. I could test it Monday because I can not have access before and I would keep you informed.

Thank you very much.

Cordially.

**Comment by smeapng** [comment]
Hi @anryko ,

I just implement the search system you've built and the result is really good.

The ability to choose multiple hosts at the time of the search would be great but it already responds strongly to the need and brings a big plus when you have a lot of hosts in the list.

Thank you very much.

Cordially.

**Comment by anryko** [comment]
@smeapng, added feature to be able to open multiple hosts after filtering (if count <= 4). Just press 'Enter' in filter field after you see hosts you want to compare.
Please let me know what you think.

**Comment by smeapng** [comment]
Hi @anryko ,

It works well, we can now simply select multiple host with a similar name.

The new presentation of the main page is much better.

Thank you for all these improvements.

if you do not see another axis of improvement on this part, you can close the issue.

Thank you.

Cordially.

**Comment by anryko** [comment]
Hi @smeapng,
Great! Merged to master.
Thanks.
