### ISSUE TITLE
allow instance selection

### ISSUE THREAD

**Issue by einsiedlerkrebs** [anryko/grafana-influx-dashboard#63]
Hey, 

thanks a lot for this project. it makes my day. I was wondering, if it would be possible, to have a more precise metrics selection, like 
```
dashboard/script/getdash.js?host=onehost.com,anotherhost.com&metric=interface&instance=eth0
```
so one could control a specific interface over all hosts.

and again, thanks!

**Comment by anryko** [comment]
Hi @einsiedlerkrebs,
I added initial implementation to the separate branch. It supports regex inputs too.
```bash
http://localhost:3000/dashboard/script/getdash.js?host=vagrant-ubuntu-precise-32&metric=disk&instance=sda1
http://localhost:3000/dashboard/script/getdash.js?host=vagrant-ubuntu-precise-32&metric=disk&instance=sd*
http://localhost:3000/dashboard/script/getdash.js?host=vagrant-ubuntu-precise-32&metric=disk&instance=sda[0-3]
```
Please test and let me know what you think.

**Comment by einsiedlerkrebs** [comment]
Hey anryko, 

that was fast. Yes, that is what I thought it should do. Thank you

eins.

**Comment by anryko** [comment]
Thanks for the nice idea @einsiedlerkrebs.
Merged to master.

**Comment by einsiedlerkrebs** [comment]
Hey, 

i am working on support for IRQ Plugin. The interrupts are numbers. `cat /proc/interrupts`. The problem is, that i have trouble with the regexing. When i have a interrupt "4" it matches "47" as well. Do you have a hint how to stop the regexing?
thanks.

eins

**Comment by anryko** [comment]
Hi @einsiedlerkrebs,
There should be no regexp match when you don't use any special characters. ```instance=4``` is translated to regexp ```/^4$/``` which should match only 4 and not 47. If you need multiple values but struggle to find exact regexp to match those you can use a list notation, like ```instance=4,6,13,101```.

for the interrupt/minute graph you should use 'apply': 'derivative(1m)' in your plugin graph configuration. Check how it is described in the getdash repository README file (// collectd disk plugin configuration).

**Comment by anryko** [comment]
Heh, I think i understood your issue only after posting the answer :). You are actually asking about plugin configuration regexp and not GET instance request... let me think about it and do some tests.

**Comment by einsiedlerkrebs** [comment]
yes. sorry, if i did not clearify this. and now i understood you answer! ;)

**Comment by anryko** [comment]
one way I can think of is to use exact regexp match
```javascript
'graph': {                                                                   
    '/^4$/': { 'apply': 'derivative(1m)' }                          
}
````
let me know if this helps :).

**Comment by einsiedlerkrebs** [comment]
yes that helps. i thought i tried this. 

cool. thanks it works.

I will see, if i can build the plugin in a bit more generic and will send you a pull request.

thanks for your help

**Comment by anryko** [comment]
you are welcome

**Comment by einsiedlerkrebs** [comment]
Thanks again. #65
