### ISSUE TITLE
Add a checkbox for choosing a host.

### ISSUE THREAD

**Issue by smeapng** [anryko/grafana-influx-dashboard#67]
Hi @anryko ,

For the easy selection of the hosts, would it be possible you to add a checkbox to select the hosts?

For example:
![image](https://cloud.githubusercontent.com/assets/13557390/16522868/9a3be202-3fa0-11e6-9852-74eb6d3d7187.png)

I do not know if this is possible because it must surely add a submit button to activate choices.

Thank you for your reflection on this subject.

Cordially.

**Comment by anryko** [comment]
Hi @smeapng,
After filtering the required hosts, if count is <=4 you can just press "Enter" to open those.

I'll investigate the possibility to add checkboxes later.
Thanks for the idea.

**Comment by smeapng** [comment]
Hi @anryko ,

Thank you for your answer.

Yes it is true that there is that possibility, but if the names of the machine differs it is not possible to do it with the enter key.

Thank you for the work done on the getDash script, it's great.

Cordially.

**Comment by smeapng** [comment]
Hello @anryko ,

To solve this problem of checkbox, I finally create a generic dashboard that gathers the metrics that are common to all my hosts with a variable to choose the name of the hosts and create in this dashboard a link that calls the script getdash See all metrics).

As this I can select several hosts easily and run them in the getdash script.

Here is a screenshot ("Show All Metric" link call the getdash script): :

![capture](https://cloud.githubusercontent.com/assets/13557390/21142481/b06d893a-c142-11e6-8590-5b910f427ac2.png)

Thanks to you for this script.

You can close this request if you wish.

Cordially.

**Comment by anryko** [comment]
Hey @smeapng 
Look good.
Thank you.
