### ISSUE TITLE
Add project to Grafana Dashboards page

### ISSUE THREAD

**Issue by oli-g** [anryko/grafana-influx-dashboard#74]
Hi @anryko 

Thank you for the Docker plugin addition (issue #71)! Now this dashboard is really powerful! That's why I think you should add it to the page https://grafana.net/dashboards, where the Grafana project is collecting various and useful dashboards for different data sources.

What do you think? If I'm not wrong, this dashboard would be the only one with Docker monitoring from Collectd sources. At the moment the only Docker monitoring dashboards are using Prometheus as source.

Another cool addition would be to make the server selection more user friendly and useful, maybe with autocompletion. There's an issue already opened for this: #67: can I help implementing it?

Looking forward to your reply and to improve even further this dashboard!

**Comment by anryko** [comment]
Hi @oli-g 
Thanks for your interest in the project.

Regarding Grafana Dashboards list:
I think the list is for static dashboards only. The idea there (as far as I understand) is to import JSON and get ready dashboard working. Getdash works on a lower level. It generates this JSON for you. So in theory you could query something like:
```
http://localhost:3000/dashboard/script/getdash.js?host=dev-kafka-1&metric=kafka&span=6&legend=false
```
Save it and export as a JSON. Then suggest it as a dashboard for https://grafana.net/dashboards.

Regarding  #67:
Any help is really welcome here :). [Here](https://github.com/anryko/grafana-influx-dashboard/blob/master/getdash.app.js#L730) you can find a javascript string where this functionality should be added.
